name: Manual approval

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy steps
        run: echo "Deploying to production" 
